/// <summary>
/// This is a class for creating a custom exception in C#
/// </summary>
class CustomException : Exception
{
    /// <summary>
    /// A parameterless constructor for the CustomException class
    /// </summary>
    public CustomException()
    {

    }

    /// <summary>
    /// A constructor that takes in a message for the exception
    /// </summary>
    /// <param name="message">The message to be displayed when the exception is thrown</param>
    public CustomException(string message) : base(message)
    {

    }

    /// <summary>
    /// A constructor that takes in a message and an inner exception for the exception
    /// </summary>
    /// <param name="message">The message to be displayed when the exception is thrown</param>
    /// <param name="innerException">The inner exception that caused the custom exception to be thrown</param>
    public CustomException(string message, Exception innerException) : base(message, innerException)
    {

    }

    /// <summary>
    /// A property that allows the exception's message to be retrieved
    /// </summary>
    public override string Message
    {
        get
        {
            return base.Message + " This message was generated by the CustomException class.";
        }
    }
}